name: own_the_city
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cupertino_will_pop_scope: ^1.2.1
  get_it: ^7.2.0
  logger: ^1.1.0
  go_router: ^6.0.1
  flutter_svg: ^1.1.6
  provider: ^6.0.5
  unicons: ^2.1.0
  url_strategy: ^0.2.0
  equatable: ^2.0.5
  firebase_storage: ^11.0.10
  image_picker: ^0.8.6
  geolocator: ^9.0.2
  cloud_firestore: ^4.3.1
  shared_preferences: ^2.0.15
  avatar_glow: ^2.0.2
  expandable: ^5.0.1
  firebase_database: ^10.0.9
  get: ^4.6.5
  intl: ^0.18.0
  carousel_slider: ^4.2.1
  country_state_city_picker: ^1.2.8
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 900
